[package]
name = "levenshtein_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "levenshtein_rs"
crate-type = ["cdylib"]  # Required for Python extensions

[dependencies]
pyo3 = { version = "0.23.4", features = ["extension-module"] }